[project]
name = "dsa-visualizer-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = ["textual", "rich"]

[project.optional-dependencies]
dev = ["pytest", "ruff"]

[project.scripts]
dsa = "dsa_visualizer.main:main"
